import { PluginCommonModule, VendurePlugin } from '@vendure/core';
import { PLUGIN_INIT_OPTIONS } from './constants';

export interface MpesaPluginOptions {
    /**
     * The consumer key is generated by Safaricom on registration of the app on the developer portal.
     * @see https://developer.safaricom.co.ke/APIs/Authorization
     **/
    consumerKey: string;

    /**
     * The consumer secret is generated by Safaricom on registration of the app on the developer portal.
     * @see https://developer.safaricom.co.ke/APIs/Authorization
     **/
    consumerSecret: string;

    /**
     * Sandbox or live mode
     */
    mode: 'sandbox' | 'live';
}

@VendurePlugin({
    imports: [PluginCommonModule],
    providers: [
        {
            provide: PLUGIN_INIT_OPTIONS,
            useFactory: () => MpesaPlugin.options,
        },
    ],
})
export class MpesaPlugin {
    static options: MpesaPluginOptions;

    /**
     * Initializes the plugin
   */
    static init(options: MpesaPluginOptions) {
        this.options = options;
        return MpesaPlugin;
    }
}