import { PluginCommonModule, VendurePlugin } from '@vendure/core';
import { PLUGIN_INIT_OPTIONS } from './constants';

/**
 * @description
 * Configuration options for the Mpesa payments plugin.
 */
export interface MpesaPluginOptions {
    /**
     * The consumer key is generated by Safaricom on registration of the app on the developer portal.
     * @see https://developer.safaricom.co.ke/APIs/Authorization
     **/
    consumerKey: string;

    /**
     * The consumer secret is generated by Safaricom on registration of the app on the developer portal.
     * @see https://developer.safaricom.co.ke/APIs/Authorization
     **/
    consumerSecret: string;

    /**
     * The Mpesa Daraja API environment, sandbox or live
     */
    environment: 'sandbox' | 'live';

    /**
     * @description
     * The host of your Vendure server, e.g. `'https://my-vendure.io'`.
     * This is used by Mpesa to send webhook events to the Vendure server
     */
    vendureHost: string;

    /**
     * @description
     * The unique number that is allocated to a pay bill or buy goods organization
     * @see https://developer.safaricom.co.ke/Documentation
     */
    shortCode: string;
}

@VendurePlugin({
    imports: [PluginCommonModule],
    providers: [
        {
            provide: PLUGIN_INIT_OPTIONS,
            useFactory: () => MpesaPlugin.options,
        },
    ],
})
export class MpesaPlugin {
    static options: MpesaPluginOptions;

    /**
     * Initializes the plugin
   */
    static init(options: MpesaPluginOptions) {
        this.options = options;
        return MpesaPlugin;
    }
}