/* eslint-disable @typescript-eslint/no-unused-vars */
import { RefundStates } from "@vendure/core"
import { CustomOrderFields } from "@vendure/core/dist/entity/custom-entity-fields"

declare module "@vendure/core/dist/entity/custom-entity-fields" {
    interface CustomOrderFields {
        mpesaCheckoutRequestID: string | null
    }
}

declare module "@vendure/core" {
    interface RefundStates {
        Created: never
    }
}

export interface TokenResponse {
    access_token: string
    expires_in: string
}

export interface STKPushResponse {
    MerchantRequestID: string
    CheckoutRequestID: string
    ResponseCode: string
    ResponseDescription: string
    CustomerMessage: string
}

export interface STKStatusResponse {
    ResponseCode: string
    ResponseDescription: string
    MerchantRequestID: string
    CheckoutRequestID: string
    ResultCode: string
    ResultDesc: string
}

export interface STKCallbackPayload {
    Body: {
        stkCallback: {
            MerchantRequestID: string
            CheckoutRequestID: string
            ResultCode: number
            ResultDesc: string
            CallbackMetadata?: {
                Item: {
                    Name: string
                    Value: string
                }[]
            }
        }
    }
}

export interface ReversalResponse {
    OriginatorConversationID: string
    ConversationID: string
    ResponseCode: string
    ResponseDescription: string
}

export interface ReversalCallbackPayload {
    Result: {
        ResultType: 0 | 1
        ResultCode: string
        ResultDesc: string
        OriginatorConversationID: string
        ConversationID: string
        TransactionID: string
        ResultParameters: {
            ResultParameter: {
                Key: string
                Value: string
            }[]
        }
        ReferenceData: {
            ReferenceItem: {
                Key: string
                Value: string
            }
        }
    }
}

export enum MpesaPaymentStatus {
    SUCCESS = "SUCCESS",
    FAILED = "FAILED",
    PENDING = "PENDING",
}

export interface MpesaTransactionVerification {
    status: MpesaPaymentStatus
    transactionId: string
    message: string
    paymentState?: string
}

export interface MpesaTransactionInitiation {
    success: boolean
    transactionId?: string
    message: string
}

/**
 * @description
 * Configuration options for Mpesa payment method.
 * These are configured per payment method, not at plugin level.
 */
export interface MpesaConfig {
    /**
     * The consumer key is generated by Safaricom on registration of the app on the developer portal.
     * @see https://developer.safaricom.co.ke/APIs/Authorization
     **/
    consumerKey: string

    /**
     * The consumer secret is generated by Safaricom on registration of the app on the developer portal.
     * @see https://developer.safaricom.co.ke/APIs/Authorization
     **/
    consumerSecret: string

    /**
     * The Mpesa Daraja API environment, sandbox or live
     */
    environment: "sandbox" | "live"

    /**
     * @description
     * The passkey is generated by Safaricom.
     * @see https://developer.safaricom.co.ke/APIs/MpesaExpressSimulate
     */
    passkey: string

    /**
     * @description
     * The unique number that is allocated to a pay bill or buy goods organization
     * @see https://developer.safaricom.co.ke/Documentation
     */
    shortCode: string

    /**
     * @description
     * The type of the shortcode, either paybill or till
     */
    shortCodeType: "till" | "paybill"

    /**
     * @description
     * The initiator name for B2C transactions and reversals
     */
    initiatorName: string

    /**
     * @description
     * The initiator password for B2C transactions and reversals
     */
    initiatorPassword: string

    /**
     * @description
     * The Mpesa API certificate for security credential encryption available on the Safaricom Developer Portal
     */
    apiCertificate: string

    /**
     * @description
     * The host of your Vendure server, e.g. `'https://my-vendure.io'`.
     * This is used by Mpesa to send webhook events to the Vendure server
     */
    vendureHost: string
}
