name: Test Package
on: ["pull_request"]

jobs:
    lint:
        name: Prettier formatting and linting check
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "18"
            - name: Install dependencies
              run: yarn
            - name: Is formatted and linted
              run: yarn lint
    test:
        name: Run tests
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "18"
            - name: Install dependencies
              run: yarn
            - name: Run tests
              run: yarn test